version: '3.8'

services:
  backend: # Tu aplicación Go
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    
    container_name: back-ventas
    restart: unless-stopped

    env_file:
      - .env # Carga las variables de entorno desde un archivo .env en el directorio actual
