@baseUrl = http://localhost:8080

### 🟢 GET - Obtener todos los clientes
GET http://localhost:8080/clientes

### =============================
### GET /clientes/{id}/direcciones
### Obtener direcciones de un cliente por ID
GET {{baseUrl}}/clientes/22222222-2/direcciones

### 🟢 POST - Crear nuevo cliente
POST http://localhost:8080/clientes
Content-Type: application/json

{
  "nombre": "Jeremy Vega",
  "telefono": "+569123456789",
  "email": "jere.@example.com",
  "razon_social": "",
  "rut": "19658977-5",
  "tipo_id": 2
}


### 🟡 PATCH - Actualizar cliente con ID X
### Para conservar los mismos datos poner ""
PATCH http://localhost:8080/clientes/19658977-5
Content-Type: application/json

{
  "rut": "20667647-7"
}

### 🟡 DELETE - Borrar cliente con RUT
DELETE http://localhost:8080/clientes/20667647-7