### 🟢 GET - Obtener todos los clientes
GET http://localhost:8080/clientes


### 🟢 POST - Crear nuevo cliente
POST http://localhost:8080/clientes
Content-Type: application/json

{
  "nombre": "JCliente prueba",
  "telefono": "+569123456789",
  "email": "jere.2@example.com",
  "razon_social": "",
  "rut": "19658977-5",
  "tipo_id": 2
}


### 🟡 PATCH - Actualizar cliente con ID X
### Para conservar los mismos datos poner ""
PATCH http://localhost:8080/clientes/19658977-5
Content-Type: application/json

{
  "telefono": "+569123456781"
}

### 🟡 DELETE - Borrar cliente con ID X
DELETE http://localhost:8080/clientes/7