### 🟢 GET - Obtener todos los clientes
GET http://localhost:8080/api/clientes

### 🟢 GET - Obtener cliente por rut
GET http://localhost:8080/api/clienteUnico/11111111-1


### 🟢 POST - Crear nuevo cliente
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
  "nombre": "JCliente prueba",
  "telefono": "+569123456789",
  "email": "jere.2@example.com",
  "razon_social": "",
  "rut": "20667647-7",
  "tipo_id": 2
}


### 🟡 PATCH - Actualizar cliente con RUT
### Para conservar los mismos datos poner ""
PATCH http://localhost:8080/api/clientes/20667647-7
Content-Type: application/json

{
  "telefono": "+569987654321"
}

### 🟡 DELETE - Borrar cliente con RUT
DELETE http://localhost:8080/api/clientes/20667647-7



        ### DIRECCIONES DE CLIENTES ###

### 🟢 GET - Obtener direcciones por RUT de un cliente        //esta bueno
GET http://localhost:8080/api/clientes/44444444-4/direcciones

### 🟢 POST - Crear direcciones por RUT de un cliente
POST http://localhost:8080/api/nuevaDireccion
Content-Type: application/json

{
  "rut_cliente": "44444444-4",
  "direccion": "Calle Falsa 123",
  "comuna": "Metropolitana",
  "ciudad": "Santiago"
}

### 🟡 DELETE - Eliminar dirrecion por ID 
DELETE http://localhost:8080/api/eliminarDireccion/7